name = "GraphFlux"
uuid = "a4947d25-c363-4647-b1dd-905d8b976b9e"
authors = ["Irhum Shafkat <13271155+irhum@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
CUDA = "3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
